### ISSUE TITLE
Update for Laravel 9

### ISSUE THREAD

**Issue by Gymnasiast** [conedevelopment/blade-filters#16]
Hi, I am using this nice package for some of my own projects. Recently, I tried to upgrade the dependencies for PHP 8(.1), but got stuck on the dependency on `"illuminate/support": "^6.0 || ^7.0 || ^8.0"`. I was wondering if you could add support for `illuminate/support` v9.0?

**Comment by iamgergo** [comment]
I updated the composer.json and released it, so it sould be okay now!
