### ISSUE TITLE
Request to add a tag for a new version of the package v1.0.1

### ISSUE THREAD

**Issue by piodab** [conedevelopment/blade-filters#18]
@iamgergo There is a problem with get the latest changes regarding support for Laravel version 10, version 1.0.0 requires laravel 9 . if we want compomoser to have the "minimum-stability" condition: "stable", this is not currently possible

**Comment by SlyDave** [comment]
Ran into this today, can you please do a release with the recently merged laravel 10 combability fixes so composer can find it. Thanks!

**Comment by iamgergo** [comment]
https://github.com/conedevelopment/blade-filters/releases/tag/v1.1.0
